"""whatsapp: accounts and message idempotency

Revision ID: 65d688536e1f
Revises: 459432d73455
Create Date: 2026-09-06 15:44:24.715431

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '65d688536e1f'
down_revision: str | None = '459432d73455'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_accounts',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=False),
    sa.Column('display_phone_number', sa.String(length=32), nullable=False),
    sa.Column('access_token_encrypted', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index(op.f('ix_whatsapp_accounts_phone_number_id'), 'whatsapp_accounts', ['phone_number_id'], unique=True)
    op.add_column('messages', sa.Column('whatsapp_message_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_messages_whatsapp_message_id'), 'messages', ['whatsapp_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_whatsapp_message_id'), table_name='messages')
    op.drop_column('messages', 'whatsapp_message_id')
    op.drop_index(op.f('ix_whatsapp_accounts_phone_number_id'), table_name='whatsapp_accounts')
    op.drop_table('whatsapp_accounts')
    # ### end Alembic commands ###
